### PR TITLE
Update patch path to new drupal host

### PR DESCRIPTION
**Pull request by jorrit**

### CODE REVIEW

**Comment by mike-potter** [comment]
This github project is not being used.  You need to post this as a patch to the Drupal.org project page for oa_workbench.

**Comment by jorrit** [comment]
OK, thanks. Maybe that could be noted in the description of this project?

**Comment by mike-potter** [comment]
Yep, I'm actually going to try and delete all of our old oa_* github modules since they are not being used anymore.

**Comment by jorrit** [comment]
On https://www.drupal.org/project/oa_workbench I can't see an issue queue. Is that intentional?

**Comment by mike-potter** [comment]
Opps, sorry I wasn't clear.  All oa_* related issues on drupal.org go into the main openatrium project issue queue (just so I don't have to keep track of 40 different issue queues).  Just be clear in the subject and body that your patch is for oa_workbench.

**Comment by jorrit** [comment]
I saw the links on https://www.drupal.org/project/oa_workbench right after I posted the last comment, sorry!

**Pull request closed without merging**
